version: '3.8'

services:

  mongo:
    image: mongo:6
    volumes:
      - mongo_qa:/data/db
    networks:
      - qa-net

  ms-auth:
    image: eminope/ms-auth:${VERSION}
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://mongo:27017/authdb
    networks:
      - qa-net

  ms-client:
    image: eminope/ms-client:${VERSION}
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://mongo:27017/customerdb
    networks:
      - qa-net

  ms-pedidos:
    image: eminope/ms-pedidos:${VERSION}
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://mongo:27017/customerdb
    networks:
      - qa-net

  api-gateway:
    image: eminope/ms-api-gateway:${VERSION}
    networks:
      - qa-net
  
  nginx:
    build:
      context: ./nginx  
    container_name: nginx-dev
    ports:
      - "8090:80"
    depends_on:
      - api-gateway
    networks:
      - dev-net

volumes:
  mongo_qa:

networks:
  qa-net: