version: '3.8'

services:

  mongo:
    image: mongo:6
    volumes:
      - mongo_qa:/data/db
    networks:
      - qa-net

  ms-auth:
    image: eminope/ms-auth:${VERSION}
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://mongo:27017/authdb
    networks:
      - qa-net

  demo:
    image: eminope/demo:${VERSION}
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://mongo:27017/customerdb
    networks:
      - qa-net

  ms-pedidos:
    image: eminope/ms-pedidos:${VERSION}
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://mongo:27017/customerdb
    networks:
      - qa-net

  api-gateway:
    image: eminope/ms-api-gateway:${VERSION}
    networks:
      - qa-net

  nginx:
    image: nginx:latest
    container_name: nginx-qa
    ports:
      - "8081:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - api-gateway
    networks:
      - qa-net

volumes:
  mongo_qa:

networks:
  qa-net: