version: '3.8'

services:

  mongo:
    image: mongo:6
    volumes:
      - mongo_prod:/data/db
    networks:
      - prod-net

  ms-auth:
    image: eminope/ms-auth:${VERSION}
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://mongo:27017/authdb
    networks:
      - prod-net

  ms-pedidos:
    image: eminope/ms-pedidos:${VERSION}
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://mongo:27017/customerdb
    networks:
      - prod-net

  ms-pedidos:
    image: eminope/ms-pedidos:${VERSION}
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://mongo:27017/customerdb
    networks:
      - prod-net

  api-gateway:
    image: eminope/ms-api-gateway:${VERSION}
    networks:
      - prod-net

  nginx:
    image: nginx:latest
    container_name: nginx-prod
    ports:
      - "80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - api-gateway
    networks:
      - prod-net

volumes:
  mongo_prod:

networks:
  prod-net: